create table if not exists clients (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    agency varchar(255) NULL,
    guid varchar(255) UNIQUE NOT NULL,
    first_name varchar(255) NULL,
    last_name varchar(255) NULL,
    status varchar(255) NOT NULL,
    dob date NOT NULL,
    created_date_time timestamp NOT NULL,

    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

create table if not exists notes (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comments varchar(4000) NULL,
    guid varchar(255) NOT NULL,
    modified_datetime timestamp NOT NULL,
    client_guid varchar(255) NOT NULL,
    datetime timestamp NOT NULL,
    logged_user varchar(255) NOT NULL,
    created_datetime timestamp NOT NULL,

    CONSTRAINT notes_pkey PRIMARY KEY (id)

);
ALTER TABLE notes
ADD CONSTRAINT fk_notes_to_client_guid FOREIGN KEY (client_guid) REFERENCES clients(guid);